.catalog:
  name: "ChinaLife monitoring"
  version: "v0.9.0"
  questions:
    - variable: "CADVISOR_PORT"
      label: "cadvisor port"
      description: "cadvisor port"
      type: "string"
      default: "9101"
      required: true
    - variable: NODE_EXPORTER_PORT
      label: "node exporter port"
      description: "node exporter port"
      required: true
      type: "string"
      default: "9100"
    - variable: RANCHER_HEALTH_EXPORTER_PORT
      label: "rancher health exporter port"
      description: "rancher health exporter port"
      required: true
      type: "string"
      default: "9173"
    - variable: RANCHER_BLACK_BOX_PORT
      label: "rancher black box port"
      description: "rancher black box port"
      required: true
      type: "string"
      default: "9115"
    - variable: CADVISOR_ARG
      label: "cadvisor extension parameters"
      description: "cadvisor extension parameters"
      required: true
      type: "string"
      default: "--housekeeping_interval=10s "
    - variable: CADVISOR_IMAGES
      label: "cadvisor images"
      description: "cadvisor images"
      required: true
      type: "string"
      default: "rancher/cadvisor:v0.33.0-1"
    - variable: NODE_EXPORTER_IMAGES
      label: "node exporter images"
      description: "node exporter images"
      required: true
      type: "string"
      default: "prom/node-exporter:v0.14.0"
    - variable: RANCHER_HEALTH_EXPORTER_IMAGES
      label: "rancher health exporter images"
      description: "rancher health exporter images"
      required: true
      type: "string"
      default: "maiwj/rancher1.x-exporter:2.3.1"
    - variable: RANCHER_BLACK_BOX_IMAGES
      label: "prometheus black box images"
      description: "prometheus black box images"
      required: true
      type: "string"
      default: "clcos/prom-blackbox-exporter:v0.16.0"
    - variable: RANCHER_BLACK_BOX_CONFIG_IMAGES
      label: "prometheus black box config images"
      description: "prometheus black box config images"
      required: true
      type: "string"
      default: "clcos/alpine:3.6"
    - variable: RANCHER_BLACK_BOX_CONFIG_CONTENT
      label: "prometheus black box config content"
      description: "prometheus black box config content"
      required: true
      type: "string"
      default: "modules:\n  icmp_prober:\n    prober: icmp\n    timeout: 5s\n    icmp:\n      preferred_ip_protocol: \"ip4\"\n  http_prober:\n    prober: http"
rancher-health-exporter:
  scale: 1
  health_check:
    port: 9173
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000