.catalog:
  name: "Rancher Logging"
  version: v0.3.1
  description: "Rancher Logging Collector"
  minimum_rancher_version: v1.5.0-rc1
  questions:
    - variable: elasticsearch_address_type
      label: "Elasticsearch Address Type"
      type: "enum"
      options:
        - "ip"
        - "hostname"
      default: "ip"
      required: true
    - variable: "elasticsearch_address"
      description: "elasticsearch service address ip or hostname"
      label: "Elasticsearch address"
      type: "string"
      required: true
    - variable: "log_driver"
      description: "Docker log driver"
      label: "Log Driver"
      type: "enum"
      required: true
      options:
      - json-file
      - journald
      default: "json-file"
    - variable: "log_vol_pattern"
      description: "Pattern of logging volumes name"
      label: "Volume Pattern"
      type: "string"
      required: true
      default: "rancher-logging*"
    - variable: "log_file_pattern"
      description: "Pattern of logging files name"
      label: "File Pattern"
      type: "string"
      required: true
      default: "*.log"
    - variable: "elasticsearch_index_format"
      description: "Pattern of elasticsearch index format, daily, monthly, yearly"
      label: "Index format"
      type: "string"
      required: true
      default: "%Y.%m.%d"
      type: enum
      options:
      - "%Y.%m.%d"
      - "%Y.%m."
      - "%Y."
elasticsearch:
  start_on_create: true
logging-agent:
  start_on_create: true
  metadata:
    elasticsearch_index_format: ${elasticsearch_index_format}
