name: Rancher Monitoring collector
version: v0.1.0
category: Infrastructure Services
description: Rancher Monitoring infra services 
labels:
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
  io.rancher.certified: other
