name: Prometheus
description: |
  Prometheus and friends, auto-discovering monitoring solution for Rancher deployments.
version: abc1.2_P2
category: Applications
labels:
  io.rancher.certified: rancher
